apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix-server
          image: maulikshah951995875/netflix_clone_repo:v1
          ports:
            - containerPort: 80